### PR TITLE
Add the packaging metadata to build the nanocoin snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest nanocoin in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

### CODE REVIEW

**Comment by elopio** [comment]
Hello @tdietert!

Here at ubuntu we are working in a new packaging system. And I'm starting to experiment with haskell projects. I used [quorum](https://github.com/jpmorganchase/quorum/pull/183) as the first test subject, and that lead me to your project which is very interesting. I think it will be useful for you to find new contributors from Ubuntu, and for us in Ubuntu it will be really nice to learn more about cryptocurrencies. 

And in addition to that, this will help us test if our system is good enough for haskell programmers. Any feedback you can give us will be very appreciated, and we will use it to guide our next sprints.

pura vida

**Comment by elopio** [comment]
Hey @tdietert, no comments or reasons for the rejection?

**Comment by tdietert** [comment]
Can you please explain your proposal in a bit more depth?

**Comment by elopio** [comment]
@tdietert oh, sorry, I missed your message.
The idea of the snap store is to give control to upstream about when and how they release their software to Linux. After maintaining the ubuntu archive for over 10 years, we learned the shortcomings and we are fixing them here. In order to do this, the system needs to be super secure, which we achieve with the `confinement: strict` that you will see in the snapcraft.yaml file, using apparmor and seccomp to isolate your application. The result is that people can start trying nanocoin with a single command: `sudo snap install nanocoin`, making it even easier to start learning about cryptocurrencies with your project.

**Pull request closed without merging**
